{
  parserClass="com.nevermore.uniapphelper.language.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.nevermore.uniapphelper.language.psi"
  psiImplPackage="com.nevermore.uniapphelper.language.psi.impl"

  elementTypeHolderClass="com.nevermore.uniapphelper.language.psi.SimpleTypes"
  elementTypeClass="com.nevermore.uniapphelper.language.psi.SimpleElementType"
  tokenTypeClass="com.nevermore.uniapphelper.language.psi.SimpleTokenType"

  psiImplUtilClass = "com.nevermore.uniapphelper.language.psi.impl.SimplePsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin = "com.nevermore.uniapphelper.language.psi.impl.SimpleNamedElementImpl"
  implements = "com.nevermore.uniapphelper.language.psi.SimpleNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier]
}
